apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: blog-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    notifications.argoproj.io/subscribe.on-sync-failed.slack: gitops-alerts
    notifications.argoproj.io/subscribe.on-health-degraded.slack: gitops-alerts
spec:
  project: default
  
  source:
    repoURL: https://github.com/IMarty/gitops-blog-course.git
    targetRevision: main
    path: overlays/prod
  
  destination:
    server: https://kubernetes.default.svc
    namespace: blog-prod
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  # Plus prudent en prod : attendre validation manuelle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m